- added some minor comments here and there - ISWCS10System 	- added a couple of variables: "kalmanEstimatorARcoeffs" and 	"kalmanEstimatorVariance" to have a single "#if defined" block => 	- these parameters, which vary depending on the type of channel, are used 	to build the Kalman estimators 	- taken care of the case when the channel is time invariant - TimeInvariantChannel 	- added implementation for "set" - OneChannelOrderPerOutputSMCAlgorithm 	- deleted commented stuff (debuggin?) from 	"imposeFixedNumberOfSurvivorsPerState" - BaseSystem 	- uncommented 			#define EXPORT_REAL_CHANNEL_ORDER 	to avoid the error "undefined reference to realchannelorder" in 	"OneChannelOrderPerOutputSMCAlgorithm". Anyway, it's needed by method 	"imposeFixedNumberOfSurvivorsPerState", which is never used (can't 	remember its purpose!!). This has probably been detected now due to an 	update in gcc - parameters adjusted for the new scenario with "TimeInvariantChannel" required for "Transactions On Vehicular Technology"